### PR TITLE
Allow ordering of parameters in the docs

### PR DESCRIPTION
**Pull request by fwkoch**
Introduces `_doc_order`, a list of all property names on a HasProperties class. This order will determine the order of the properties in the docs. After the docs are written, `_doc_order` is removed from the class dictionary.

Notes:
- `_doc_order` must contain ALL property names or be unspecified/empty. Otherwise an `AttributeError` will be raised on class definition.
- If `_doc_order` is not specified, the docs will be ordered alphabetically.
- `Required`/`Optional`/`Immutable` hierarchy in the docs supersedes `_doc_order`; the order will only be reflected within those sections.

See: https://github.com/3ptscience/properties/issues/58

### CODE REVIEW

**Comment by bsmithyman** [comment]
@ThomasMatern: In the current implementation, an empty list isn't distinguishable from an unspecified one (b/c it is `.pop(...)`'d from the kwargs with a default of `[]`. I guess the alternative would be to have `.pop('_doc_order', None)` and then `if _doc_order is None: ...`, or perhaps just `.pop('_doc_order', sorted(_props))`. Is there an advantage to one over the other?

**Comment by ThomasMatern** [comment]
@bsmithyman my question is not about the current implementation (it follows what's documented in the pull request), my question is why we want to even allow this. The user/developer should have only two options: specify _doc_order as a complete list of properties or not specify it at all. Setting it to anything else (empty list, None, incomplete list) should raise a value error. Unless there is an actual use-case that I'm missing?

**Comment by bsmithyman** [comment]
@ThamasMatern: Makes sense. I don't have a strong opinion, but it would not be hard to raise an error. I think what is nice about the current structure is that regardless of whether the list is specified or not, it is put through the same process & the same validation is run. This cuts down on code replication.

Taking @fwkoch's existing code & making it a bit more strict, it is an easy fix to change lines 90–100 to:

```python
_doc_order = classdict['_doc_order'] if '_doc_order' in classdict else sorted(_props)
if not isinstance(_doc_order, (list, tuple)):
    raise AttributeError(
        '_doc_order must be a list of property names'
    )
if sorted(list(_doc_order)) != sorted(_props):
    raise AttributeError(
        '_doc_order must be unspecified or contain ALL property names'
    )
```

and, in fact, replacing the first line with this is close to the same thing & a bit shorter:

```python
_doc_order = classdict.pop('_doc_order', sorted(_props))
```

@fwkoch: You had some arguments I think for `AttributeError` vs. `ValueError`; beyond that I am not picky. Hope this helps?

**Comment by fwkoch** [comment]
@ThomasMatern, @bsmithyman - There needs to be some value of `_doc_order` that goes back to the default `sorted(_props)` behaviour in order for subclasses to override invalid `_doc_order` inherited from parent class.

I think it makes more sense for this to be `None` though rather than an empty list, similar to @bsmithyman's first comment.

```python
import properties

class WithDocOrder(properties.HasProperties):
    _doc_order = ['b', 'a']
    a = properties.Integer('int a')
    b = properties.Integer('int b')

class WithoutDocOrder(WithDocOrder):
    _doc_order = None
    c = properties.Integer('int c')
```

All that said, hopefully alphabetizing will be sufficient for most cases. `_doc_order` will be an "advanced" and probably undocumented feature.

**Comment by ThomasMatern** [comment]
@fwkoch that makes sense. I didn't think of subclasses.

**Pull request merged**
