### PR TITLE
Restructure files

### PR DESCRIPTION
**Pull request by fwkoch**
base.py and basic.py were getting excessively long. This PR restructures classes into more files:

- hasproperties.py: `HasProperties` and `PropertyMetaclass`
- properties.py: `GettableProperty`, `DynamicProperty`, `Property`
- primitive.py: `Bool`, `Int`, `String`, etc.
- basic.py: `StringChoice`, `Color`, `Uuid`, `File`, etc.
- nested.py: `Instance`, `List`, `Union`
- math.py: unchanged
- image.py: renamed from images.py

### CODE REVIEW

**Comment by fwkoch** [comment]
This also includes minor additions (mostly docstrings) and fixes (notably, `assert_valid` recursion problems) to `DynamicProperty`.

**Comment by bsmithyman** [comment]
I know we avoided exporting `PropertyTerms` in the `__init__.py` file to keep the namespace clean, but it is being used heavily in some compute-related code. Can we lock down where it is going to stay, since previously it was `from properties.basic import PropertyTerms`, and now it is `from properties.properties import PropertyTerms`? I appreciate that we want the main interface to be as clean as possible, but in that case we need some kind of structure to ensure that deep imports don't move around from version to version.

**Comment by rowanc1** [comment]
Can we also rename `properties.py` to `base.py` to avoid confusion.

**Comment by bsmithyman** [comment]
I wonder if we want to define some kind of `properties.meta` or something, that exposes some of these under-the-hood structures in a fixed location? So, `from properties import ...` would include the `HasProperties` class, and the individual `Property` subclasses. In that case, `from properties.meta import ...` would give things like `PropertyTerms`, `PropertyMetaclass`, etc.

**Comment by fwkoch** [comment]
@bsmithyman - I agree this reshuffle is not ideal. I'm happy to leave it as-is, if that's preferable, and just allow longer files. We could also use different names than those I proposed (for example `properties.py` could remain `basic.py`, and we could also have `primitive.py` and ... `something_else.py` for `File`, `StringChoice`, `Uuid`, etc...).

Alternatively, we could keep the namespace the same (`properties.base`, `properties.basic`, etc., but break up the namespaces into separate files (like in `properties.basic` also import the primitives).

@rowanc1 - `properties.py` used to be a subset of `basic.py`; `base.py` was `HasProperties`, etc. so that is all extra confusing...

**Comment by fwkoch** [comment]
I think this PR should be refactored to not break backwards compatibility, either by just leaving files long or importing classes into multiple namespaces... not sure which is uglier...

**Comment by bsmithyman** [comment]
I'm not so worried in this case; all the code using `PropertyTerms` is under heavy dev, and a refactor is not that big a deal. However, I would like to have some stability moving forward if we can. And, I would think that as we build up more users from other external orgs, the resistance to change the location of some of these things will only grow. So, I guess I would say, "let's figure out what is best and then implement it, so we don't have to change it more than once"...? Not sure if that makes sense.

Thanks!

**Comment by fwkoch** [comment]
I'm going to close this PR un-merged. I think this will be put on hold for now (and we will just tolerate longer files), but any future restructure will maintain backwards compatibility with the namespace as-is. This can be done by moving from:
```
properties
  |- __init__.py
  |- base.py
  |- basic.py
  |- math.py
  ...
```
to
```
properties
  |- __init__.py
  |- base
  |    |- __init__.py
  |    |- base.py
  |    |- nested.py
  |- basic
  |    |- __init__.py
  |    |- base.py
  |    |- primitives.py
  |    ...
  |- math.py
  ...
```

**Pull request closed without merging**
